<script lang="ts">

    // --- Logic ---
    import { cn } from '@lib/utils';
    import type { EmojiProps } from ".."
    
    let {
        children,
        class: className,
        emojiClass = $bindable(''),
        style,
        ...rest
    }: any = $props();


    // Setup Emoji's class
    let emojiCls = $state(cn(emojiClass, className));
    $effect(() => {
        emojiCls = cn(emojiClass, className)
    })

    console.log(style)

</script>

<span class={emojiCls} {style}>🧻</span>

<!--@component
    Generated by SvelteForge🔥
-->

