<script lang="ts">

    // --- Logic ---
    import { cn, min_max } from '@lib/utils';
    import type { Props } from ".."
    import { onMount } from 'svelte';
    import { PaperPs } from '../..';
    
    let {
        children,
        class: className,
        paperPsClass = $bindable('')
    }: Props = $props();

    // Setup PaperPs's class
    let paperPsCls = $state(cn(paperPsClass, className));
    $effect(() => {
        paperPsCls = cn(paperPsClass, className)
    })

    let emojis = $state([])

    function random() {
        // Generate random X and Y for translate
        const x = min_max(-100, 0);
        const y = min_max(0, 0);
        return `transform: translate(${x}%, ${y}%);`;
    }

    onMount(() => {
        setTimeout(() => {
            const emojis = document.querySelectorAll(".paper-emoji")

            emojis.forEach(element => {
                // Apply random translate on mount
                const x = min_max(1500, 3000);
                const y = min_max(-10, 1000);
                element.style.transform = `translate(${x}%, ${y}%)`;
            });
        }, 100)
    })

</script>

{#each {length: 50} as _, i}
    <PaperPs.Emoji class={cn("absolute paper-emoji left-0 top-[20%] duration-1000")} style={random()}/>
{/each}

<!--@component
    Generated by SvelteForge🔥
-->
