<script lang="ts">
	// --- Logic ---
	import { cn } from '@lib/utils';
	import { Root, type GeneratorProps } from '..';

	let {
		children,
		class: className,
		generatorClass = $bindable(''),
        particleClass = $bindable(''),
		count = $bindable(1),
        position = $bindable(undefined),
        ...rest
	}: GeneratorProps = $props();

	// Setup Generator's class
	let generatorCls = $state(cn(generatorClass, className));
	$effect(() => {
		generatorCls = cn(generatorClass, className);
	});
</script>

<div class={generatorCls}>
	{#each Array(count) as _}
		<Root class={particleClass} {position} {...rest}>
			{@render children?.()}
		</Root>
	{/each}
</div>

<!--@component
    Generated by SvelteForge🔥
-->
