<script lang="ts">
	// --- Components ---
	import { Flex, Separator, Drawer } from '@lib/components';

	// --- Logic ---
	import { cn } from '@lib/utils';
	import type { MenuProps } from '..';
	import { getCtx } from '../ctx';
	import { fade } from 'svelte/transition';
	import { directives } from '@root/lib/internal/directives';
	import { Row } from '../../flex';

	let {
		children,
		class: className,
		menuClass = $bindable(
			`animate duration-500
			shrink-0 overflow-hidden 
			flex flex-col 
			w-[300px] h-full 
			bg-primary
			pt-[10px]
			border-solid border-0 border-r border-def border-primary`
		),

		classBackdrop,
		...rest
	}: MenuProps = $props();

	// Setup Menu's class
	let menuCls = $state(cn(menuClass, className));
	$effect(() => {
		menuCls = cn(menuClass, className);
	});

	// Get Drawer Context
	const { show$, close_drawer } = getCtx();
</script>

<!-- Actual Menu -->
<div
	use:directives
	class={cn(menuClass, (!$show$ && 'w-[60px]') || 'pt-6')}
	onoutclick={() => close_drawer()}
>
	<!-- Hamborger Button -->
	<Flex.Row class="w-full h-fit relative z-0">
		{#if $show$}
			<div
				transition:fade={{ duration: 200 }}
				class="absolute left-8 size-10 flex flex-col items-center justify-center overflow-hidden"
			>
				<!-- <IconLogo class="size-14 shrink-0 opacity-99" /> -->
			</div>
		{/if}
		<Drawer.Hamburger class="z-1" />
	</Flex.Row>

	<!-- Children-->
	<Flex.Col class={cn('animate shrink-0 w-15 box-border border-r-0 pl-[10px] border-primary border-none gap-3', $show$ && 'px-8 w-full')}>
		{@render children?.()}
	</Flex.Col>

	<Separator />
</div>
<!--@component
    Generated by SvelteForge🔥
-->
