<script lang="ts">
	// --- Logic ---
	import { cn, explosion } from '@lib/utils';
	import type { Props } from '..';
	import { Frame, Header } from 'sk-clib';
	import { fade, fly } from 'svelte/transition';
	import { onMount } from 'svelte';
	import characterAltImage from '@assets/seethruFade.png';

	let {
		class: className,
		portraitClass = $bindable('z-10'),
		name = $bindable('SAM'),
		...rest
	}: Props = $props();

	// Setup Portrait's class
	let portraitCls = $state(cn(portraitClass, className));
	$effect(() => {
		portraitCls = cn(portraitClass, className);
	});

	onMount(() => {
		const config = { duration: 300, fill: 'forwards', easing: 'ease-in-out' };

		// Character
		
		character_ref?.animate([{ opacity: '0' }, { opacity: '1' }], {
			duration: 800,
			fill: 'forwards',
			easing: 'ease-in-out'
		});

		character_alt?.animate([{ opacity: '0.6' }, { opacity: '0' }], {
			duration: 2000,
			fill: 'forwards',
			easing: 'ease-in-out'
		});

		character_alt?.animate([{ transform: 'scale(2)' }, { transform: 'scale(1.6)' }], {
			duration: 1600,
			fill: 'forwards',
			easing: 'ease-in-out'
			
		});

	});

	let character_ref: HTMLDivElement | undefined = $state(undefined);
	let character_alt: HTMLElement | undefined = $state(undefined);
</script>

<Frame class="relative size-full">
	<div class="z-3 flex h-full flex-col items-center">
		<img bind:this={character_ref} {...rest} class={portraitCls} />
		<Header class={cn('z-14')} xxl>{name}</Header>

		<!-- wide flame -->
		 <img
			bind:this={character_alt}
			src={characterAltImage}
			alt="fire"
			class={cn('absolute top-[9%] left-[47%] transform -translate-x-1/2 z-12 w-2000 duration-400 ')}
		/>
	
	</div>
</Frame>

<!--@component
    Generated by SvelteForge🔥
-->
