<script lang="ts">
	// --- Logic ---
	import { cn, explosion } from '@lib/utils';
	import type { Props } from '..';
	import { Frame, Header } from 'sk-clib';
	import { fade, fly } from 'svelte/transition';
	import { onMount } from 'svelte';
	import StoneSpike from '@assets/scaryspike.png';

	let {
		class: className,
		portraitClass = $bindable('z-1'),
		name = $bindable('SAM'),
		...rest
	}: Props = $props();

	// Setup Portrait's class
	let portraitCls = $state(cn(portraitClass, className));
	$effect(() => {
		portraitCls = cn(portraitClass, className);
	});

	onMount(() => {
		const config = { duration: 300, fill: 'forwards', easing: 'ease-in-out' };

		// Character
		character_ref?.animate([{ transform: 'translateY(80%)' }, {}], config as any);

		// spike 1
		spike1_ref?.animate([{ opacity: '0' }, { opacity: '1' }], {
			duration: 100,
			fill: 'forwards',
			easing: 'ease-in-out'
		});

		spike1_ref?.animate(
			[{ transform: 'rotate(0) translateY(80%)' }, { transform: 'rotate(20deg)' }],
			config as any
		);

		// spike 2
		spike2_ref?.animate([{ opacity: '0' }, { opacity: '1' }], {
			duration: 100,
			fill: 'forwards',
			easing: 'ease-in-out'
		});

		spike2_ref?.animate(
			[{ transform: 'rotate(0deg) translateY(80%)' }, { transform: 'rotate(-40deg)' }],
			config as any
		);
	});

	let character_ref: HTMLDivElement | undefined = $state(undefined);
	let spike1_ref: HTMLElement | undefined = $state(undefined);
	let spike2_ref: HTMLElement | undefined = $state(undefined);
</script>

<Frame class="relative size-full">
	<div class="z-3 flex h-full flex-col items-center">
		<img bind:this={character_ref} {...rest} class={portraitCls} />
		<Header xxl class={'z-5'} >{name}</Header>

		<!--shatter explosions -->
		<img
			bind:this={spike1_ref}
			src={StoneSpike}
			alt="scarySpike"
			class={cn('absolute top-70 -left-20 z-1 size-[20vw] duration-600')}
		/>
		<img
			bind:this={spike2_ref}
			src={StoneSpike}
			alt="scarySpike"
			class={cn('absolute top-70 left-50 z-1 size-[20vw] duration-600')}
		/>
	</div>
</Frame>

<!--@component
    Generated by SvelteForge🔥
-->
