<script lang="ts">
	// --- Logic ---
	import { cn, explosion } from '@lib/utils';
	import type { Props } from '..';
	import { Frame, Header } from 'sk-clib';
	import { fade, fly } from 'svelte/transition';
	import { onMount } from 'svelte';
	import blueprint2 from '@assets/blueprint2.png';
	import blueprint3 from '@assets/blueprint3.png';

	let {
		class: className,
		portraitClass = $bindable('z-1'),
		name = $bindable('SAM'),
		...rest
	}: Props = $props();

	// Setup Portrait's class
	let portraitCls = $state(cn(portraitClass, className));
	$effect(() => {
		portraitCls = cn(portraitClass, className);
	});

	onMount(() => {
		const config = { duration: 300, fill: 'forwards', easing: 'ease-in-out' };

		// blueprint 1
		character_ref?.animate([{ transform: 'translateX(-80%)' }, {}], config as any);

		// blueprint 2
		blueprint_2?.animate([{ opacity: '0' }, { opacity: '1' }], {
			duration: 1800,
			fill: 'forwards',
			easing: 'ease-in-out'
		});

		blueprint_2?.animate(
			[{ transform: 'rotate(0) scale(2)'  }, { transform: 'rotate(25deg) scale(0.9)' }],
			{
				duration: 1600,
				fill: 'forwards',
				easing: 'ease-in-out'
			}
		);

	


		// blueprint 3
		blueprint_3?.animate([{ opacity: '0' }, { opacity: '1' }], {
			duration: 3500,
			fill: 'forwards',
			easing: 'ease-in-out'
		});

		blueprint_3?.animate(
			[{ transform: 'rotate(0) scale(2)'  }, { transform: 'rotate(-20deg) scale(0.9)' }],
			{
				duration: 3500,
				fill: 'forwards',
				easing: 'ease-in-out'
			}
		);

	});

	let character_ref: HTMLDivElement | undefined = $state(undefined);
	let blueprint_2: HTMLElement | undefined = $state(undefined);
	let blueprint_3: HTMLElement | undefined = $state(undefined);
</script>

<Frame class="relative size-full">
	<div class="z-1 flex h-full flex-col items-center">
		<img bind:this={character_ref} {...rest} class={portraitCls} />
		<Header xxl>{name}</Header>

		<!--shatter explosions -->
		<img
			bind:this={blueprint_2}
			src={blueprint2}
			alt="a blueprint"
			class={cn('absolute top-5 left-50 z-2 aspect-0/2  duration-400')}
		/>
		<img
			bind:this={blueprint_3}
			src={blueprint3}
			alt="another blueprint"
			class={cn('absolute top-40 -left-50 z-3 aspect-0/2  duration-400')}
		/>
	</div>
</Frame>

<!--@component
    Generated by SvelteForge🔥
-->
