<script lang="ts">
	// --- Logic ---
	import { cn, explosion } from '@lib/utils';
	import type { Props } from '..';
	import { Frame, Header } from 'sk-clib';
	import { fade, fly } from 'svelte/transition';
	import { onMount } from 'svelte';
	import ShatterExplosion from '@assets/shatterExplosion.png';

	let {
		class: className,
		portraitClass = $bindable('z-99'),
		name = $bindable('SAM'),
		...rest
	}: Props = $props();

	// Setup Portrait's class
	let portraitCls = $state(cn(portraitClass, className));
	$effect(() => {
		portraitCls = cn(portraitClass, className);
	});

	onMount(() => {
		const config = { duration: 300, fill: 'forwards', easing: 'ease-in-out' };

		// Character
		character_ref?.animate([{ transform: 'translateX(80%)' }, {}], config as any);

		// Explosion 1
		explosion_ref?.animate([{ opacity: '0' }, { opacity: '1' }], {
			duration: 100,
			fill: 'forwards',
			easing: 'ease-in-out'
		});

		explosion_ref?.animate(
			[{ transform: 'rotate(0)' }, { transform: 'rotate(25deg)' }],
			config as any
		);

		// Explosion 2
		explosion2_ref?.animate([{ opacity: '0' }, { opacity: '1' }], {
			duration: 100,
			fill: 'forwards',
			easing: 'ease-in-out'
		});

		explosion2_ref?.animate(
			[{ transform: 'rotate(0)' }, { transform: 'rotate(125deg)' }],
			config as any
		);
	});

	let character_ref: HTMLDivElement | undefined = $state(undefined);
	let explosion_ref: HTMLElement | undefined = $state(undefined);
	let explosion2_ref: HTMLElement | undefined = $state(undefined);
</script>

<Frame class="relative size-full">
	<div class="z-3 flex h-full flex-col items-center">
		<img bind:this={character_ref} {...rest} class={portraitCls} />
		<Header xxl>{name}</Header>

		<img
			bind:this={explosion_ref}
			src={ShatterExplosion}
			alt="explosion"
			class={cn('absolute top-2 -right-60 z-1 size-[20vw] duration-400')}
		/>
		<img
			bind:this={explosion2_ref}
			src={ShatterExplosion}
			alt="explosion"
			class={cn('absolute top-40 -right-50 z-1 size-[20vw] duration-400')}
		/>
	</div>
</Frame>

<!--@component
    Generated by SvelteForge🔥
-->
