<script lang="ts">
	// --- Logic ---
	import { cn, explosion } from '@lib/utils';
	import type { Props } from '..';
	import { Frame, Header } from 'sk-clib';
	import { fade, fly } from 'svelte/transition';
	import { onMount } from 'svelte';
	import { PaperPs } from '../..';


	let {
		class: className,
		portraitClass = $bindable('z-99'),
		name = $bindable('SAM'),
		...rest
	}: Props = $props();

	// Setup Portrait's class
	let portraitCls = $state(cn(portraitClass, className));
	$effect(() => {
		portraitCls = cn(portraitClass, className);
	});

	onMount(() => {
		const config = { duration: 300, fill: 'forwards', easing: 'ease-in-out' };

		// Character
		character_ref?.animate([{ transform: 'translateX(-80%)' }, {}], config as any);
	});

	let character_ref: HTMLDivElement | undefined = $state(undefined);
	let explosion_ref: HTMLElement | undefined = $state(undefined);
	let explosion2_ref: HTMLElement | undefined = $state(undefined);
</script>

<Frame class="relative size-full">
	<div class="z-3 flex h-full flex-col items-center">
		<img bind:this={character_ref} {...rest} class={portraitCls} />
		<Header xxl>{name}</Header>
		<PaperPs.Root/>
	
	</div>
</Frame>

<!--@component
    Generated by SvelteForge🔥
-->
